/* ============================================================
   IANIS men's — catalogul pozelor din galeria de pe colectii.html
   ------------------------------------------------------------
   CUM ADAUGI O POZĂ NOUĂ (fără alte modificări de cod):
     1. Pui fișierul în folderul „imagini/”, cu numele slotului
        (ex. imagini/pantofi20.png — vezi prefixul fiecărei categorii mai jos).
     2. Cauți slotul cu acel număr și schimbi  activ: false  în  activ: true.
     3. Opțional, dar recomandat pentru Google: adaugi o descriere scurtă,
        de exemplu  { n: 20, activ: true, alt: 'Pantofi derby negri din piele' }

   Pozele apar în galerie exact în ordinea din listele de mai jos.
   O categorie fără nicio poză activă (ex. cămăși) își ascunde automat filtrul
   și reapare singură când activezi prima poză.
   ============================================================ */

/* Categoriile galeriei. „w” și „h” sunt dimensiunile folosite pentru
   atributele width/height ale pozelor (evită săriturile de layout la încărcare). */
var CATEGORII = [
  {
    id: "costume",
    nume: "Costume",
    prefix: "poza",   /* imagini/poza1.png, imagini/poza2.png, … */
    w: 1200, h: 1600, raport: "portret",
    altImplicit: "Costum bărbătesc în trei piese la IANIS men's Focșani"
  },
  {
    id: "sacouri",
    nume: "Sacouri",
    prefix: "sacou",   /* imagini/sacou1.png, imagini/sacou2.png, … */
    w: 1170, h: 1540, raport: "portret",
    altImplicit: "Sacou bărbătesc la IANIS men's Focșani"
  },
  {
    id: "camasi",
    nume: "Cămăși",
    prefix: "camasa",   /* imagini/camasa1.png, imagini/camasa2.png, … */
    w: 1170, h: 1550, raport: "portret",
    altImplicit: "Cămașă bărbătească la IANIS men's Focșani"
  },
  {
    id: "jeans",
    nume: "Jeans",
    prefix: "jeans",   /* imagini/jeans1.png, imagini/jeans2.png, … */
    w: 1170, h: 1455, raport: "portret",
    altImplicit: "Blugi bărbătești la IANIS men's Focșani"
  },
  {
    id: "geci",
    nume: "Geci",
    prefix: "geaca",   /* imagini/geaca1.png, imagini/geaca2.png, … */
    w: 1170, h: 1550, raport: "portret",
    altImplicit: "Geacă bărbătească la IANIS men's Focșani"
  },
  {
    id: "paltoane",
    nume: "Paltoane",
    prefix: "palton",   /* imagini/palton1.png, imagini/palton2.png, … */
    w: 1170, h: 1550, raport: "portret",
    altImplicit: "Palton bărbătesc la IANIS men's Focșani"
  },
  {
    id: "pantofi",
    nume: "Pantofi",
    prefix: "pantofi",   /* imagini/pantofi1.png, imagini/pantofi2.png, … */
    w: 1170, h: 860, raport: "peisaj",
    altImplicit: "Pantofi eleganți pentru bărbați la IANIS men's Focșani"
  }
];

/* Sloturile fiecărei categorii: 1–100, în ordinea în care apar în galerie. */
var PRODUSE = {
  costume: [
    /* --- poze active (25) --- */
    { n:  23, activ: true,  alt: "Costum verde mentă în trei piese, cu nasturi închiși la culoare" },
    { n:  11, activ: true,  alt: "Costum coniac cu vestă și cămașă bleu, într-o nuanță caldă de maro" },
    { n:  21, activ: true,  alt: "Costum bej nisip în trei piese, cu cămașă bleu și cravată închisă la culoare" },
    { n:   1, activ: true,  alt: "Costume bărbătești în zeci de culori, expuse pe umerașe în magazinul IANIS men's din Focșani" },
    { n:   4, activ: true,  alt: "Costum negru clasic în trei piese, cu vestă, în magazinul IANIS men's" },
    { n:  12, activ: true,  alt: "Costum verde petrol cu vestă, cu sacou la doi nasturi" },
    { n:  22, activ: true,  alt: "Costum maro-gri cu vestă, purtat cu cămașă albă și cravată cu model" },
    { n:  14, activ: true,  alt: "Costum gri perlat cu vestă la șase nasturi și pantalon asortat" },
    { n:  13, activ: true,  alt: "Costum bleumarin în trei piese, cu cămașă albă și cravată închisă la culoare" },
    { n:   2, activ: true,  alt: "Costum bărbătesc bej în trei piese, cu vestă, purtat cu cămașă bleu și cravată neagră cu model auriu" },
    { n:  24, activ: true,  alt: "Costum verde salvie cu vestă și cravată neagră cu model auriu" },
    { n:  20, activ: true,  alt: "Costum maro cu vestă la cinci nasturi și cămașă bleu" },
    { n:   8, activ: true,  alt: "Costum taupe în trei piese, cu nasturi maro și cravată cu model auriu" },
    { n:   7, activ: true,  alt: "Costum albastru deschis cu vestă, potrivit pentru nunți și evenimente de zi" },
    { n:  19, activ: true,  alt: "Costum caramel cu vestă și cămașă albă, în magazinul IANIS men's" },
    { n:   3, activ: true,  alt: "Costum verde turcoaz cu vestă și cămașă albă, fotografiat de aproape" },
    { n:   6, activ: true,  alt: "Costum gri antracit în trei piese, cu sacou la un rând de nasturi" },
    { n:   5, activ: true,  alt: "Bărbat în costum negru cu vestă și cravată cu model auriu" },
    { n:  25, activ: true,  alt: "Costum coniac în trei piese, cu vestă și pantalon asortate" },
    { n:  16, activ: true,  alt: "Costum camel în trei piese, cu nasturi aurii, în interiorul magazinului" },
    { n:  10, activ: true,  alt: "Costum verde salvie în trei piese, fotografiat la intrarea în magazin" },
    { n:   9, activ: true,  alt: "Costum gri deschis cu vestă și nasturi aurii, purtat cu cămașă albă" },
    { n:  18, activ: true,  alt: "Costum bleumarin cu vestă și cravată cu model auriu, fotografiat în lumină naturală" },
    { n:  15, activ: true,  alt: "Costum maro coniac cu vestă, purtat cu cămașă albă" },
    { n:  17, activ: true,  alt: "Costum maro ruginiu în trei piese, cu vestă asortată" },
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ],
  sacouri: [
    /* --- poze active (13) --- */
    { n:   4, activ: true,  alt: "Sacou bleumarin, croială slim, purtat cu pantaloni negri" },
    { n:   2, activ: true,  alt: "Sacou bej nisip, croială slim, purtat cu pantaloni negri" },
    { n:   6, activ: true,  alt: "Sacou verde închis, croială slim, purtat cu pantaloni negri" },
    { n:   3, activ: true,  alt: "Sacou bleu deschis, cu rever ascuțit, purtat peste tricou negru" },
    { n:  13, activ: true,  alt: "Sacou albastru electric, croială slim, purtat peste tricou negru" },
    { n:   7, activ: true,  alt: "Sacou negru antracit, cu rever ascuțit, purtat peste tricou negru" },
    { n:  11, activ: true,  alt: "Sacou bleumarin cu rever ascuțit, purtat peste tricou negru" },
    { n:   9, activ: true,  alt: "Sacou crem, cu un nasture, purtat peste tricou negru" },
    { n:  10, activ: true,  alt: "Sacou roz pe umeraș, în magazinul IANIS men's din Focșani" },
    { n:   8, activ: true,  alt: "Sacou bleu pastel, croială slim, purtat cu pantaloni negri" },
    { n:   1, activ: true,  alt: "Sacou bărbătesc gri deschis, cu un nasture, purtat peste tricou negru" },
    { n:   5, activ: true,  alt: "Sacou maro-vișiniu, cu un nasture, purtat peste tricou negru" },
    { n:  12, activ: true,  alt: "Sacou verde închis, cu un nasture, purtat cu pantaloni negri" },
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:  14, activ: false },
    { n:  15, activ: false },
    { n:  16, activ: false },
    { n:  17, activ: false },
    { n:  18, activ: false },
    { n:  19, activ: false },
    { n:  20, activ: false },
    { n:  21, activ: false },
    { n:  22, activ: false },
    { n:  23, activ: false },
    { n:  24, activ: false },
    { n:  25, activ: false },
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ],
  camasi: [
    /* --- nicio poză activă deocamdată --- */
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:   1, activ: false },
    { n:   2, activ: false },
    { n:   3, activ: false },
    { n:   4, activ: false },
    { n:   5, activ: false },
    { n:   6, activ: false },
    { n:   7, activ: false },
    { n:   8, activ: false },
    { n:   9, activ: false },
    { n:  10, activ: false },
    { n:  11, activ: false },
    { n:  12, activ: false },
    { n:  13, activ: false },
    { n:  14, activ: false },
    { n:  15, activ: false },
    { n:  16, activ: false },
    { n:  17, activ: false },
    { n:  18, activ: false },
    { n:  19, activ: false },
    { n:  20, activ: false },
    { n:  21, activ: false },
    { n:  22, activ: false },
    { n:  23, activ: false },
    { n:  24, activ: false },
    { n:  25, activ: false },
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ],
  jeans: [
    /* --- poze active (11) --- */
    { n:  11, activ: true,  alt: "Blugi albastru clasic, croială slim, cu eticheta pe ei" },
    { n:   5, activ: true,  alt: "Blugi bleumarin închis, croială conică, purtați cu tricou alb" },
    { n:   1, activ: true,  alt: "Blugi bărbătești albastru deschis, croială dreaptă, fotografiați întinși" },
    { n:   2, activ: true,  alt: "Blugi negri spălăciți, croială slim, fotografiați întinși" },
    { n:   4, activ: true,  alt: "Blugi gri spălăcit, croială slim, purtați cu sneakers albi" },
    { n:  10, activ: true,  alt: "Blugi albaștri, croială conică, purtați cu tricou alb" },
    { n:   7, activ: true,  alt: "Blugi albastru-gri închis, croială slim" },
    { n:   8, activ: true,  alt: "Blugi albastru mediu, ușor uzați, croială slim" },
    { n:   3, activ: true,  alt: "Blugi negri, croială slim, cu eticheta pe ei" },
    { n:   9, activ: true,  alt: "Blugi albastru foarte deschis, cu rupturi, croială skinny" },
    { n:   6, activ: true,  alt: "Blugi albaștri, croială slim, purtați cu sneakers albi" },
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:  12, activ: false },
    { n:  13, activ: false },
    { n:  14, activ: false },
    { n:  15, activ: false },
    { n:  16, activ: false },
    { n:  17, activ: false },
    { n:  18, activ: false },
    { n:  19, activ: false },
    { n:  20, activ: false },
    { n:  21, activ: false },
    { n:  22, activ: false },
    { n:  23, activ: false },
    { n:  24, activ: false },
    { n:  25, activ: false },
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ],
  geci: [
    /* --- nicio poză activă deocamdată --- */
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:   1, activ: false },
    { n:   2, activ: false },
    { n:   3, activ: false },
    { n:   4, activ: false },
    { n:   5, activ: false },
    { n:   6, activ: false },
    { n:   7, activ: false },
    { n:   8, activ: false },
    { n:   9, activ: false },
    { n:  10, activ: false },
    { n:  11, activ: false },
    { n:  12, activ: false },
    { n:  13, activ: false },
    { n:  14, activ: false },
    { n:  15, activ: false },
    { n:  16, activ: false },
    { n:  17, activ: false },
    { n:  18, activ: false },
    { n:  19, activ: false },
    { n:  20, activ: false },
    { n:  21, activ: false },
    { n:  22, activ: false },
    { n:  23, activ: false },
    { n:  24, activ: false },
    { n:  25, activ: false },
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ],
  paltoane: [
    /* --- nicio poză activă deocamdată --- */
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:   1, activ: false },
    { n:   2, activ: false },
    { n:   3, activ: false },
    { n:   4, activ: false },
    { n:   5, activ: false },
    { n:   6, activ: false },
    { n:   7, activ: false },
    { n:   8, activ: false },
    { n:   9, activ: false },
    { n:  10, activ: false },
    { n:  11, activ: false },
    { n:  12, activ: false },
    { n:  13, activ: false },
    { n:  14, activ: false },
    { n:  15, activ: false },
    { n:  16, activ: false },
    { n:  17, activ: false },
    { n:  18, activ: false },
    { n:  19, activ: false },
    { n:  20, activ: false },
    { n:  21, activ: false },
    { n:  22, activ: false },
    { n:  23, activ: false },
    { n:  24, activ: false },
    { n:  25, activ: false },
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ],
  pantofi: [
    /* --- poze active (19) --- */
    { n:   8, activ: true,  alt: "Pantofi eleganți coniac, alături de perechi negre, gri și bleumarin" },
    { n:  18, activ: true,  alt: "Pantofi bleumarin cu model perforat, fotografiați pe raftul din magazin" },
    { n:  11, activ: true,  alt: "Pantofi eleganți maro deschis, alături de modele negre, gri și bleumarin" },
    { n:  12, activ: true,  alt: "Pantofi eleganți gri închis, alături de o pereche coniac și una bleumarin" },
    { n:   6, activ: true,  alt: "Pantofi eleganți negri cu textură croco, alături de perechi maro, coniac și bleumarin" },
    { n:  15, activ: true,  alt: "Pantofi coniac cu bombeu cusut, alături de perechi bleumarin, maro și negre" },
    { n:   3, activ: true,  alt: "Mocasini coniac cu cataramă, fotografiați alături de aceleași modele în negru și bleumarin" },
    { n:  14, activ: true,  alt: "Pantofi derby bleumarin, alături de modele negre, coniac și gri" },
    { n:   5, activ: true,  alt: "Mocasini din velur crem cu canaf, alături de variante negre, camel, maro și bleumarin" },
    { n:  13, activ: true,  alt: "Pantofi eleganți verde închis, alături de perechi maro, negre lucioase și coniac" },
    { n:  16, activ: true,  alt: "Pantofi eleganți gri, alături de o pereche neagră și una coniac" },
    { n:  19, activ: true,  alt: "Pantofi coniac clasici, alături de perechi negre și maro" },
    { n:  10, activ: true,  alt: "Pantofi oxford coniac, alături de perechi negre și maro" },
    { n:   9, activ: true,  alt: "Pantofi eleganți bleumarin din piele lucioasă, alături de modele negre, gri și coniac" },
    { n:   7, activ: true,  alt: "Pantofi derby negri din piele, alături de modele coniac și bleumarin" },
    { n:   4, activ: true,  alt: "Pantofi eleganți gri închis cu model perforat, alături de perechi coniac și bleumarin" },
    { n:   1, activ: true,  alt: "Pantofi eleganți din piele, model derby maro închis, expuși alături de perechi negre, coniac și bleumarin" },
    { n:   2, activ: true,  alt: "Mocasini bărbătești coniac cu cataramă metalică, alături de variante negre, bleumarin și maro" },
    { n:  17, activ: true,  alt: "Pantofi bleumarin din piele lucioasă, alături de modele negre, coniac și gri" },
    /* --- sloturi libere: pune fișierul în imagini/ și treci activ pe true --- */
    { n:  20, activ: false },
    { n:  21, activ: false },
    { n:  22, activ: false },
    { n:  23, activ: false },
    { n:  24, activ: false },
    { n:  25, activ: false },
    { n:  26, activ: false },
    { n:  27, activ: false },
    { n:  28, activ: false },
    { n:  29, activ: false },
    { n:  30, activ: false },
    { n:  31, activ: false },
    { n:  32, activ: false },
    { n:  33, activ: false },
    { n:  34, activ: false },
    { n:  35, activ: false },
    { n:  36, activ: false },
    { n:  37, activ: false },
    { n:  38, activ: false },
    { n:  39, activ: false },
    { n:  40, activ: false },
    { n:  41, activ: false },
    { n:  42, activ: false },
    { n:  43, activ: false },
    { n:  44, activ: false },
    { n:  45, activ: false },
    { n:  46, activ: false },
    { n:  47, activ: false },
    { n:  48, activ: false },
    { n:  49, activ: false },
    { n:  50, activ: false },
    { n:  51, activ: false },
    { n:  52, activ: false },
    { n:  53, activ: false },
    { n:  54, activ: false },
    { n:  55, activ: false },
    { n:  56, activ: false },
    { n:  57, activ: false },
    { n:  58, activ: false },
    { n:  59, activ: false },
    { n:  60, activ: false },
    { n:  61, activ: false },
    { n:  62, activ: false },
    { n:  63, activ: false },
    { n:  64, activ: false },
    { n:  65, activ: false },
    { n:  66, activ: false },
    { n:  67, activ: false },
    { n:  68, activ: false },
    { n:  69, activ: false },
    { n:  70, activ: false },
    { n:  71, activ: false },
    { n:  72, activ: false },
    { n:  73, activ: false },
    { n:  74, activ: false },
    { n:  75, activ: false },
    { n:  76, activ: false },
    { n:  77, activ: false },
    { n:  78, activ: false },
    { n:  79, activ: false },
    { n:  80, activ: false },
    { n:  81, activ: false },
    { n:  82, activ: false },
    { n:  83, activ: false },
    { n:  84, activ: false },
    { n:  85, activ: false },
    { n:  86, activ: false },
    { n:  87, activ: false },
    { n:  88, activ: false },
    { n:  89, activ: false },
    { n:  90, activ: false },
    { n:  91, activ: false },
    { n:  92, activ: false },
    { n:  93, activ: false },
    { n:  94, activ: false },
    { n:  95, activ: false },
    { n:  96, activ: false },
    { n:  97, activ: false },
    { n:  98, activ: false },
    { n:  99, activ: false },
    { n: 100, activ: false }
  ]
};
